### ISSUE TITLE
hook_client_redis does not work anymore

### ISSUE THREAD

**Issue by mheimschild** [senecajs/seneca-redis-pubsub-transport#41]
`TypeError: Cannot read property 'sync' of undefined
    at internals.Utils.prepare_request (/seneca-redis-test/node_modules/seneca-transport/lib/transport-utils.js:137:32)
    at Seneca.<anonymous> (/seneca-redis-test/node_modules/seneca-redis-transport/redis-transport.js:112:25)
    at Seneca.send (/seneca-redis-test/node_modules/seneca-transport/lib/transport-utils.js:324:14)
    at Seneca.transport_client (/seneca-redis-test/node_modules/seneca/lib/api.js:202:25)`

**Comment by mypipsen** [comment]
Experiencing the same issue.

**Comment by mheimschild** [comment]
here is a workaround:

`require('seneca')({
        legacy: {
                meta: true,
        }
});`
